version: '3'
networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: 182.17.0.0/16
          gateway: 182.17.0.1

services:
  das-indexer:
    image: slagga/das-indexer:latest
    restart: always
    working_dir: /app
    entrypoint: [ "/app/das-indexer", "--config", "/app/config/config.yaml" ]
    ports:
      - "8121:8121"
      - "8122:8122"
      - "8123:8123"
    volumes:
      - $PWD/config/config.yaml:/app/config/config.yaml
    depends_on:
      - mysql
      - redis
    networks:
      - mynetwork

  mysql:
    image: mysql/mysql-server:8.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - $PWD/mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: das_account_indexer
      TZ: Asia/Shanghai
      # This allows ip ranges from 182.17.0.1 to 182.17.255.255 to connect to root
      MYSQL_ROOT_HOST: "182.17.%.%"
    networks:
      - mynetwork

  redis:
    image: redis:5.0
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork
