server:
  net: 1 # 1-mainnet 2-testnet
  http_server_addr: ":8121"
  http_server_addr_indexer: ":8122"
  http_server_addr_reverse: ":8123"
chain:
  ckb_url: "http://127.0.0.1:8114"
  index_url: "http://127.0.0.1:8116"
  current_block_number: 4872287
  confirm_num: 4
  concurrency_num: 100
db:
  mysql:
    addr: "127.0.0.1:3306"
    user: "root"
    password: "123456"
    db_name: "das_account_indexer"
    max_open_conn: 100
    max_idle_conn: 50
cache:
  redis:
    addr: "127.0.0.1:6379"
    password: ""
    db_num: 0
